require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'capybara.gemspec'
    
############# New Cops #####################

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true

#################### Lint ################################

Lint/Debugger:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
  IgnoredPatterns:
    - '\s+# rubocop'
    - '^\s*#'
    - '^\s*(raise|warn) '
    - " if ENV\\['DEBUG'\\]$"
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'apparition.gemspec'
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/MethodParameterName:
  AllowedNames:
    - 'el'
    - 'id'
    - 'c'
    - 'x'
    - 'y'
    - 'on'
    - 'ip'
    - '_'

Style/GlobalVars:
  Exclude:
    - 'spec/capybara-webkit/**/*.rb'

Style/RaiseArgs:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Security/YAMLLoad:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleWording:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/NamedSubject:
  Exclude:
    - 'spec/capybara-webkit/**/*.rb'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/capybara-webkit/**/*.rb'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/capybara-webkit/**/*.rb'

RSpec/DescribeMethod:
  Exclude:
    - 'spec/capybara-webkit/**/*.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
